name: "coding standards"

on: ["pull_request", "push"]

jobs:
  coding-standards:
    name: "coding standards"

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:           ['macos-latest', 'ubuntu-latest']
        hhvm:         ['4.83', '4.84']
        dependencies: ['lowest', 'highest', 'locked']
        experimental: [false]

        include:
          - { hhvm: 'stable',  os: 'ubuntu-latest', experimental: false, dependencies: 'lowest'  }
          - { hhvm: 'stable',  os: 'ubuntu-latest', experimental: false, dependencies: 'locked'  }
          - { hhvm: 'stable',  os: 'ubuntu-latest', experimental: false, dependencies: 'highest' }

          - { hhvm: 'nightly', os: 'ubuntu-latest', experimental: true , dependencies: 'lowest'  }
          - { hhvm: 'nightly', os: 'ubuntu-latest', experimental: true , dependencies: 'highest' }

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing hhvm"
        uses: "azjezz/setup-hhvm@v1.0.0"
        with:
          version: ${{ matrix.hhvm }}

      - name: "installing lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress"

      - name: "installing highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"

      - name: "lint"
        continue-on-error: ${{ matrix.experimental }}
        run: "hhvm vendor/bin/hhast-lint"
